<?php

namespace AppBundle\Repository;

/**
 * CesarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CesarRepository extends \Doctrine\ORM\EntityRepository
{
}
