<?php

namespace AppBundle\Repository;

/**
 * JetonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JetonsRepository extends \Doctrine\ORM\EntityRepository
{
}
