<?php

namespace AppBundle\Repository;

/**
 * specialitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class specialitesRepository extends \Doctrine\ORM\EntityRepository
{
}
